/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lostgames;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.dao.ProdutoDAO;

/**
 *
 * @author Luis
 */
public class tela_Menu extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_Menu() {
        initComponents();
        Cadastro.setVisible(false);
        Catalogo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        panel_Background = new javax.swing.JPanel();
        Modelo = new javax.swing.JPanel();
        Catalogo = new javax.swing.JPanel();
        PanelCatalogo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Catalogo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Label_Busca = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_CampoBusca = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        Cadastro = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_Buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Cadastrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        panel_BarraSuperior = new javax.swing.JPanel();
        panel_SuperiorEsq = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_Titulo = new javax.swing.JLabel();
        panel_Fundo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        panel_Inicio = new javax.swing.JPanel();
        menu_Home = new javax.swing.JLabel();
        panel_Catalogo = new javax.swing.JPanel();
        menu_Catalogo = new javax.swing.JLabel();
        panel_Usuarios = new javax.swing.JPanel();
        menu_Usuarios = new javax.swing.JLabel();
        panel_Sair = new javax.swing.JPanel();
        menu_Sair = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lux Games");
        setMinimumSize(new java.awt.Dimension(1366, 720));

        panel_Background.setBackground(new java.awt.Color(255, 255, 255));
        panel_Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Modelo.setBackground(new java.awt.Color(255, 255, 255));

        Catalogo.setBackground(new java.awt.Color(255, 255, 255));
        Catalogo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        Catalogo.setLayout(new javax.swing.OverlayLayout(Catalogo));

        PanelCatalogo.setBackground(new java.awt.Color(255, 255, 255));

        table_Catalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Quantidade", "Preço", "Marca", "Data Fabricação", "Categoria", "Tags"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Catalogo);

        jPanel1.setBackground(new java.awt.Color(237, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Label_Busca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Busca.setText("Nome:");

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Descrição:");

        txt_CampoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CampoBuscaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Quantidade:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Preço:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Marca:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Data Fabr:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Pesquisar)
                .addGap(396, 396, 396))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Label_Busca))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_CampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField9)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Busca)
                    .addComponent(txt_CampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(btn_Pesquisar)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout PanelCatalogoLayout = new javax.swing.GroupLayout(PanelCatalogo);
        PanelCatalogo.setLayout(PanelCatalogoLayout);
        PanelCatalogoLayout.setHorizontalGroup(
            PanelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelCatalogoLayout.setVerticalGroup(
            PanelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Catalogo.add(PanelCatalogo);

        Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");

        panel_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        panel_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");

        javax.swing.GroupLayout panel_BuscarLayout = new javax.swing.GroupLayout(panel_Buscar);
        panel_Buscar.setLayout(panel_BuscarLayout);
        panel_BuscarLayout.setHorizontalGroup(
            panel_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarLayout.createSequentialGroup()
                .addGap(1503, 1503, 1503)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_BuscarLayout.setVerticalGroup(
            panel_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BUSCAR", panel_Buscar);

        panel_Cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        panel_Cadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADASTRAR");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("USERNAME");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("SENHA");

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("E-MAIL");

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("CONFIRMAR SENHA");

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_CadastrarLayout = new javax.swing.GroupLayout(panel_Cadastrar);
        panel_Cadastrar.setLayout(panel_CadastrarLayout);
        panel_CadastrarLayout.setHorizontalGroup(
            panel_CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(847, Short.MAX_VALUE))
        );
        panel_CadastrarLayout.setVerticalGroup(
            panel_CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CADASTRAR", panel_Cadastrar);

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
                .addContainerGap())
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ModeloLayout = new javax.swing.GroupLayout(Modelo);
        Modelo.setLayout(ModeloLayout);
        ModeloLayout.setHorizontalGroup(
            ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModeloLayout.setVerticalGroup(
            ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_BarraSuperior.setBackground(new java.awt.Color(0, 139, 139));

        panel_SuperiorEsq.setBackground(new java.awt.Color(48, 53, 76));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(89, 95, 124));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lux Games™");

        javax.swing.GroupLayout panel_SuperiorEsqLayout = new javax.swing.GroupLayout(panel_SuperiorEsq);
        panel_SuperiorEsq.setLayout(panel_SuperiorEsqLayout);
        panel_SuperiorEsqLayout.setHorizontalGroup(
            panel_SuperiorEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SuperiorEsqLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(44, 44, 44))
        );
        panel_SuperiorEsqLayout.setVerticalGroup(
            panel_SuperiorEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SuperiorEsqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        txt_Titulo.setText("Início");

        javax.swing.GroupLayout panel_BarraSuperiorLayout = new javax.swing.GroupLayout(panel_BarraSuperior);
        panel_BarraSuperior.setLayout(panel_BarraSuperiorLayout);
        panel_BarraSuperiorLayout.setHorizontalGroup(
            panel_BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BarraSuperiorLayout.createSequentialGroup()
                .addComponent(panel_SuperiorEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_BarraSuperiorLayout.setVerticalGroup(
            panel_BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_SuperiorEsq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_BarraSuperiorLayout.createSequentialGroup()
                .addComponent(txt_Titulo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_Fundo.setBackground(new java.awt.Color(59, 65, 94));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/Logo_adobespark.png"))); // NOI18N

        panel_Inicio.setBackground(new java.awt.Color(0, 139, 139));
        panel_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        panel_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_Home.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Home.setForeground(new java.awt.Color(255, 255, 255));
        menu_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/Inicio.png"))); // NOI18N
        menu_Home.setText(" Início      ");
        menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_HomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_InicioLayout = new javax.swing.GroupLayout(panel_Inicio);
        panel_Inicio.setLayout(panel_InicioLayout);
        panel_InicioLayout.setHorizontalGroup(
            panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_InicioLayout.setVerticalGroup(
            panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Home, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        panel_Catalogo.setBackground(new java.awt.Color(59, 65, 94));
        panel_Catalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_Catalogo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Catalogo.setForeground(new java.awt.Color(255, 255, 255));
        menu_Catalogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/Catalogo.png"))); // NOI18N
        menu_Catalogo.setText("Catálogo ");
        menu_Catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_CatalogoLayout = new javax.swing.GroupLayout(panel_Catalogo);
        panel_Catalogo.setLayout(panel_CatalogoLayout);
        panel_CatalogoLayout.setHorizontalGroup(
            panel_CatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_CatalogoLayout.setVerticalGroup(
            panel_CatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Catalogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        panel_Usuarios.setBackground(new java.awt.Color(59, 65, 94));
        panel_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_Usuarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        menu_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/Usuario.png"))); // NOI18N
        menu_Usuarios.setText("Usuários ");
        menu_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_UsuariosLayout = new javax.swing.GroupLayout(panel_Usuarios);
        panel_Usuarios.setLayout(panel_UsuariosLayout);
        panel_UsuariosLayout.setHorizontalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_UsuariosLayout.setVerticalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        panel_Sair.setBackground(new java.awt.Color(59, 65, 94));
        panel_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_Sair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Sair.setForeground(new java.awt.Color(255, 255, 255));
        menu_Sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/Sair.png"))); // NOI18N
        menu_Sair.setText(" Sair ");
        menu_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_SairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_SairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_SairLayout = new javax.swing.GroupLayout(panel_Sair);
        panel_Sair.setLayout(panel_SairLayout);
        panel_SairLayout.setHorizontalGroup(
            panel_SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_SairLayout.setVerticalGroup(
            panel_SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_FundoLayout = new javax.swing.GroupLayout(panel_Fundo);
        panel_Fundo.setLayout(panel_FundoLayout);
        panel_FundoLayout.setHorizontalGroup(
            panel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_FundoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(Logo)
                .addContainerGap())
            .addComponent(panel_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_FundoLayout.setVerticalGroup(
            panel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_BackgroundLayout = new javax.swing.GroupLayout(panel_Background);
        panel_Background.setLayout(panel_BackgroundLayout);
        panel_BackgroundLayout.setHorizontalGroup(
            panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BackgroundLayout.createSequentialGroup()
                .addComponent(panel_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel_BarraSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_BackgroundLayout.setVerticalGroup(
            panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BackgroundLayout.createSequentialGroup()
                .addComponent(panel_BarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_BackgroundLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//INÍCIO MENU
    //MOUSE PASSA PELO BOTÃO
    private void menu_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseEntered
        if(!txt_Titulo.getText().equals("Início")){
            panel_Inicio.setBackground(new Color(69,75,104));
        }
    }//GEN-LAST:event_menu_HomeMouseEntered

    private void menu_UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseEntered
        if(!Cadastro.isVisible()){
            panel_Usuarios.setBackground(new Color(69,75,104));
        }
    }//GEN-LAST:event_menu_UsuariosMouseEntered

    private void menu_CatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseEntered
        if(!Catalogo.isVisible()){
            panel_Catalogo.setBackground(new Color(69,75,104));
        }
    }//GEN-LAST:event_menu_CatalogoMouseEntered

    //MOUSE SAI DO BOTÃO
    private void menu_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseExited
        if(!txt_Titulo.getText().equals("Início")){
            panel_Inicio.setBackground(new Color(59,65,94));
        }
    }//GEN-LAST:event_menu_HomeMouseExited

    private void menu_CatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseExited
        if(!Catalogo.isVisible()){
            panel_Catalogo.setBackground(new Color(59,65,94));
        }
    }//GEN-LAST:event_menu_CatalogoMouseExited

    private void menu_UsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseExited
        if(!Cadastro.isVisible()){
            panel_Usuarios.setBackground(new Color(59,65,94));
        }
    }//GEN-LAST:event_menu_UsuariosMouseExited

    private void menu_SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_SairMouseExited
        panel_Sair.setBackground(new Color(59,65,94));
    }//GEN-LAST:event_menu_SairMouseExited

    //MOUSE CLICA NO BOTÃO
    private void menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseClicked
        //Deixa o botão selecionado
        
        //seleciona o botão
        panel_BarraSuperior.setBackground(new Color(0,139,139));
        panel_SuperiorEsq.setBackground(new Color(48,53,76));
        panel_Inicio.setBackground(new Color(0,139,139));
        txt_Titulo.setText("Início");
        
        //Desceleciona outros botões
        panel_Catalogo.setBackground(new Color(59,65,94));
        panel_Usuarios.setBackground(new Color(59,65,94));
        
        Cadastro.setVisible(false);
        Catalogo.setVisible(false);
    }//GEN-LAST:event_menu_HomeMouseClicked

    private void menu_CatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseClicked
        //Deixa o botão selecionado
        panel_BarraSuperior.setBackground(new Color(255,153,0));
        panel_SuperiorEsq.setBackground(new Color(255,102,0));
        panel_Catalogo.setBackground(new Color(255,102,0));
        txt_Titulo.setText("Catálogo");
        
        //Desceleciona os outros botões
        panel_Usuarios.setBackground(new Color(59,65,94));
        panel_Inicio.setBackground(new Color(59,65,94));
                
        Cadastro.setVisible(false);
        Catalogo.setVisible(true);
    }//GEN-LAST:event_menu_CatalogoMouseClicked

    private void menu_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseClicked
        //Deixa o botão selecionado
        panel_BarraSuperior.setBackground(new Color(255,0,0));
        panel_SuperiorEsq.setBackground(new Color(204,0,0));
        panel_Usuarios.setBackground(new Color(204,0,0));
        txt_Titulo.setText("Usuários");
        
        //Desceleciona os outros botões
        panel_Catalogo.setBackground(new Color(59,65,94));
        panel_Inicio.setBackground(new Color(59,65,94));
        
        Cadastro.setVisible(true);
        Catalogo.setVisible(false);
    }//GEN-LAST:event_menu_UsuariosMouseClicked

    private void menu_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_SairMouseClicked
        dispose();
        tela_Login_new tela_Login_new = new tela_Login_new();
        tela_Login_new.setVisible(true);
    }//GEN-LAST:event_menu_SairMouseClicked

    //SAIR
    private void menu_SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_SairMouseEntered
        panel_Sair.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_SairMouseEntered

//FIM MENU
    
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) table_Catalogo.getModel();
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produto p: pdao.listar()){
            modelo.addRow(new Object[]{
               p.getId(),
               p.getNome(),
               p.getDescrição(),
               p.getEstoque(),
               p.getPreço(),
               p.getMarca(),
               p.getDataFabricação(),
               p.getIdCategorias(),
               p.getIdTags()
            });
        }
    }
    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void txt_CampoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CampoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CampoBuscaActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Catalogo;
    private javax.swing.JLabel Label_Busca;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Modelo;
    private javax.swing.JPanel PanelCatalogo;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel menu_Catalogo;
    private javax.swing.JLabel menu_Home;
    private javax.swing.JLabel menu_Sair;
    private javax.swing.JLabel menu_Usuarios;
    private javax.swing.JPanel panel_Background;
    private javax.swing.JPanel panel_BarraSuperior;
    private javax.swing.JPanel panel_Buscar;
    private javax.swing.JPanel panel_Cadastrar;
    private javax.swing.JPanel panel_Catalogo;
    private javax.swing.JPanel panel_Fundo;
    private javax.swing.JPanel panel_Inicio;
    private javax.swing.JPanel panel_Sair;
    private javax.swing.JPanel panel_SuperiorEsq;
    private javax.swing.JPanel panel_Usuarios;
    private javax.swing.JTable table_Catalogo;
    private javax.swing.JTextField txt_CampoBusca;
    private javax.swing.JLabel txt_Titulo;
    // End of variables declaration//GEN-END:variables
}
