/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lostgames;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Luis
 */
public class tela_Menu extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_Menu() {
        initComponents();
        Cadastro.setVisible(false);
        Catalogo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Modelo = new javax.swing.JPanel();
        Catalogo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Cadastro = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_Buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Cadastrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        panel_BarraSuperior = new javax.swing.JPanel();
        panel_Fundo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        panel_Inicio = new javax.swing.JPanel();
        menu_Home = new javax.swing.JLabel();
        panel_Catalogo = new javax.swing.JPanel();
        menu_Catalogo = new javax.swing.JLabel();
        panel_Usuarios = new javax.swing.JPanel();
        menu_Usuarios = new javax.swing.JLabel();
        panel_Sair = new javax.swing.JPanel();
        menu_Sair = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 720));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Modelo.setBackground(new java.awt.Color(51, 51, 51));

        Catalogo.setBackground(new java.awt.Color(255, 255, 255));
        Catalogo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        Catalogo.setLayout(new javax.swing.OverlayLayout(Catalogo));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        Catalogo.add(jPanel1);

        Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");

        panel_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        panel_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");

        javax.swing.GroupLayout panel_BuscarLayout = new javax.swing.GroupLayout(panel_Buscar);
        panel_Buscar.setLayout(panel_BuscarLayout);
        panel_BuscarLayout.setHorizontalGroup(
            panel_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1026, Short.MAX_VALUE))
        );
        panel_BuscarLayout.setVerticalGroup(
            panel_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(537, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BUSCAR", panel_Buscar);

        panel_Cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        panel_Cadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADASTRAR");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("USERNAME");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("SENHA");

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("E-MAIL");

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("CONFIRMAR SENHA");

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_CadastrarLayout = new javax.swing.GroupLayout(panel_Cadastrar);
        panel_Cadastrar.setLayout(panel_CadastrarLayout);
        panel_CadastrarLayout.setHorizontalGroup(
            panel_CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(847, Short.MAX_VALUE))
        );
        panel_CadastrarLayout.setVerticalGroup(
            panel_CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CADASTRAR", panel_Cadastrar);

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout ModeloLayout = new javax.swing.GroupLayout(Modelo);
        Modelo.setLayout(ModeloLayout);
        ModeloLayout.setHorizontalGroup(
            ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE))
        );
        ModeloLayout.setVerticalGroup(
            ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
        );

        panel_BarraSuperior.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout panel_BarraSuperiorLayout = new javax.swing.GroupLayout(panel_BarraSuperior);
        panel_BarraSuperior.setLayout(panel_BarraSuperiorLayout);
        panel_BarraSuperiorLayout.setHorizontalGroup(
            panel_BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1363, Short.MAX_VALUE)
        );
        panel_BarraSuperiorLayout.setVerticalGroup(
            panel_BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        panel_Fundo.setBackground(new java.awt.Color(153, 0, 0));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/Logo_adobespark.png"))); // NOI18N

        panel_Inicio.setBackground(new java.awt.Color(153, 0, 0));
        panel_Inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_InicioMouseEntered(evt);
            }
        });

        menu_Home.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Home.setForeground(new java.awt.Color(255, 255, 255));
        menu_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/home (1).png"))); // NOI18N
        menu_Home.setText("INÍCIO");
        menu_Home.setBorder(new javax.swing.border.MatteBorder(null));
        menu_Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_HomeMouseMoved(evt);
            }
        });
        menu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_HomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_InicioLayout = new javax.swing.GroupLayout(panel_Inicio);
        panel_Inicio.setLayout(panel_InicioLayout);
        panel_InicioLayout.setHorizontalGroup(
            panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_InicioLayout.setVerticalGroup(
            panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        panel_Catalogo.setBackground(new java.awt.Color(153, 0, 0));
        panel_Catalogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu_Catalogo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Catalogo.setForeground(new java.awt.Color(255, 255, 255));
        menu_Catalogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/book-alt.png"))); // NOI18N
        menu_Catalogo.setText("CATÁLOGO");
        menu_Catalogo.setBorder(new javax.swing.border.MatteBorder(null));
        menu_Catalogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseMoved(evt);
            }
        });
        menu_Catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_CatalogoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_CatalogoLayout = new javax.swing.GroupLayout(panel_Catalogo);
        panel_Catalogo.setLayout(panel_CatalogoLayout);
        panel_CatalogoLayout.setHorizontalGroup(
            panel_CatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_CatalogoLayout.setVerticalGroup(
            panel_CatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Catalogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panel_Usuarios.setBackground(new java.awt.Color(153, 0, 0));
        panel_Usuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu_Usuarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        menu_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/address-book.png"))); // NOI18N
        menu_Usuarios.setText("USUÁRIOS");
        menu_Usuarios.setBorder(new javax.swing.border.MatteBorder(null));
        menu_Usuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseMoved(evt);
            }
        });
        menu_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_UsuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_UsuariosLayout = new javax.swing.GroupLayout(panel_Usuarios);
        panel_Usuarios.setLayout(panel_UsuariosLayout);
        panel_UsuariosLayout.setHorizontalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_UsuariosLayout.setVerticalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        panel_Sair.setBackground(new java.awt.Color(153, 0, 0));
        panel_Sair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu_Sair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menu_Sair.setForeground(new java.awt.Color(255, 255, 255));
        menu_Sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostgames/Images/sign-out.png"))); // NOI18N
        menu_Sair.setText("SAIR");
        menu_Sair.setBorder(new javax.swing.border.MatteBorder(null));
        menu_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_SairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_SairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_SairLayout = new javax.swing.GroupLayout(panel_Sair);
        panel_Sair.setLayout(panel_SairLayout);
        panel_SairLayout.setHorizontalGroup(
            panel_SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_SairLayout.setVerticalGroup(
            panel_SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_FundoLayout = new javax.swing.GroupLayout(panel_Fundo);
        panel_Fundo.setLayout(panel_FundoLayout);
        panel_FundoLayout.setHorizontalGroup(
            panel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Catalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_FundoLayout.createSequentialGroup()
                        .addComponent(Logo)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(panel_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_FundoLayout.setVerticalGroup(
            panel_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(panel_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panel_BarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panel_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panel_BarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //MOUSE PASSA PELO BOTÃO
    private void menu_HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseMoved
        panel_Inicio.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_HomeMouseMoved

    private void menu_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseEntered
        panel_Inicio.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_HomeMouseEntered

    private void menu_UsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseMoved
        panel_Usuarios.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_UsuariosMouseMoved

    private void menu_UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseEntered
        panel_Usuarios.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_UsuariosMouseEntered

    private void menu_CatalogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseMoved
        panel_Catalogo.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_CatalogoMouseMoved

    private void menu_CatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseEntered
        panel_Catalogo.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_CatalogoMouseEntered

    private void panel_InicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_InicioMouseEntered
    }//GEN-LAST:event_panel_InicioMouseEntered

    
    
    
    //MOUSE SAI DO BOTÃO
    private void menu_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseExited
        panel_Inicio.setBackground(new Color(153,0,0)); 
    }//GEN-LAST:event_menu_HomeMouseExited

    private void menu_CatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseExited
        panel_Catalogo.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_menu_CatalogoMouseExited

    private void menu_UsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseExited
        panel_Usuarios.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_menu_UsuariosMouseExited

    private void menu_SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_SairMouseExited
        panel_Sair.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_menu_SairMouseExited





    //MOUSE CLICA NO BOTÃO
    private void menu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HomeMouseClicked
        //Deixa o botão selecionado
        panel_Inicio.setBorder(BorderFactory.createEtchedBorder(Color.yellow, Color.black));
        
        //Desceleciona os outros botões
        panel_Catalogo.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        panel_Usuarios.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        Cadastro.setVisible(false);
        Catalogo.setVisible(false);
    }//GEN-LAST:event_menu_HomeMouseClicked

    private void menu_CatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CatalogoMouseClicked
        //Deixa o botão selecionado
        panel_Catalogo.setBorder(BorderFactory.createEtchedBorder(Color.yellow, Color.black));
        
        
        //Desceleciona os outros botões
        panel_Inicio.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        panel_Usuarios.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        Cadastro.setVisible(false);
        Catalogo.setVisible(true);
    }//GEN-LAST:event_menu_CatalogoMouseClicked

    private void menu_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UsuariosMouseClicked
        //Deixa o botão selecionado
        panel_Usuarios.setBorder(BorderFactory.createEtchedBorder(Color.yellow, Color.black));
        
        
        //Desceleciona os outros botões
        panel_Inicio.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        panel_Catalogo.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        Cadastro.setVisible(true);
        Catalogo.setVisible(false);
    }//GEN-LAST:event_menu_UsuariosMouseClicked

    private void menu_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_SairMouseClicked
        dispose();
        tela_Login_new tela_Login_new = new tela_Login_new();
        tela_Login_new.setVisible(true);
    }//GEN-LAST:event_menu_SairMouseClicked

    private void menu_SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_SairMouseEntered
        panel_Sair.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_menu_SairMouseEntered

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Catalogo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Modelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel menu_Catalogo;
    private javax.swing.JLabel menu_Home;
    private javax.swing.JLabel menu_Sair;
    private javax.swing.JLabel menu_Usuarios;
    private javax.swing.JPanel panel_BarraSuperior;
    private javax.swing.JPanel panel_Buscar;
    private javax.swing.JPanel panel_Cadastrar;
    private javax.swing.JPanel panel_Catalogo;
    private javax.swing.JPanel panel_Fundo;
    private javax.swing.JPanel panel_Inicio;
    private javax.swing.JPanel panel_Sair;
    private javax.swing.JPanel panel_Usuarios;
    // End of variables declaration//GEN-END:variables
}
